[package]
name = "arcsearch"
version = "0.2.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arcconfig = "0.2"
clap = { version = "4.4.11", features = ["cargo"] }
colored = "2.0.0"
regex = "1.8.2"
